const OFFSET_VALUE_TO_TOKEN_VALUE = 2;
const OFFSET_VALUE_TO_THEME_VALUE = 2;
const OFFSET_VALUE_TO_MODE_VALUE = 4;
const CHARACTER_TO_INDICATE_VARIABLE = '$';
const TOKENS_LAYER_NAME = 'TOKENS';
const BRAND_LAYER_NAME = 'BRANDNAME';
const THEME_LAYER_NAME = 'THEMENAME';
const MODE_LAYER_NAME = 'MODENAME';



module.exports = { 
    OFFSET_VALUE_TO_TOKEN_VALUE, 
    OFFSET_VALUE_TO_THEME_VALUE,
    OFFSET_VALUE_TO_MODE_VALUE,
    CHARACTER_TO_INDICATE_VARIABLE,
    TOKENS_LAYER_NAME,
    BRAND_LAYER_NAME,
    THEME_LAYER_NAME,
    MODE_LAYER_NAME
};