const OFFSET_VALUE_TO_TOKEN_VALUE = 2;
const CHARACTER_TO_INDICATE_VARIABLE = '$';
const TOKENS_LAYER_NAME = 'TOKENS';
const BRAND_LAYER_NAME = 'BRANDNAME';

module.exports = { 
    OFFSET_VALUE_TO_TOKEN_VALUE, 
    CHARACTER_TO_INDICATE_VARIABLE,
    TOKENS_LAYER_NAME,
    BRAND_LAYER_NAME
};